CREATE DATABASE BaseDeDadosHbsis
GO
USE BaseDeDadosHbsis
GO
CREATE TABLE [dbo].[Marcas] (
    [Id]     INT        IDENTITY (1, 1) NOT NULL,
    [Codigo] INT        NULL,
    [Nome]   NCHAR (20) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO
CREATE TABLE [dbo].[ModelosVeiculos] (
    [Id]          INT        IDENTITY (1, 1) NOT NULL,
    [Codigo]      INT        NULL,
    [Modelo]      NCHAR (50) NULL,
    [MarcaCodigo] INT        NULL,
    [TipoCodigo]  INT        NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO
CREATE TABLE [dbo].[Tipos]
(
    [Id] INT NOT NULL PRIMARY KEY iDENTITY (1,1), 
    [Codigo] INT NULL, 
    [Nome] NCHAR(10) NULL
)
GO
INSERT INTO Tipos (Codigo,Nome) Values (0,'Carro'), (1,'Moto')
GO
insert into Marcas (Codigo,Nome) values (1,'Audi')
insert into Marcas (Codigo,Nome) values (2,'BMW')
insert into Marcas (Codigo,Nome) values (3,'Chevrolet')
insert into Marcas (Codigo,Nome) values (4,'Citröen')
insert into Marcas (Codigo,Nome) values (5,'Fiat')
insert into Marcas (Codigo,Nome) values (6,'Ford')
insert into Marcas (Codigo,Nome) values (7,'Honda')
insert into Marcas (Codigo,Nome) values (8,'Hyundai')
insert into Marcas (Codigo,Nome) values (9,'Jeep')
insert into Marcas (Codigo,Nome) values (10,'Kia')
insert into Marcas (Codigo,Nome) values (11,'Mitsubishi')
insert into Marcas (Codigo,Nome) values (12,'Nissan')
insert into Marcas (Codigo,Nome) values (13,'Peugeot')
insert into Marcas (Codigo,Nome) values (14,'Renault')
insert into Marcas (Codigo,Nome) values (15,'Toyota')
insert into Marcas (Codigo,Nome) values (16,'Volkswagen')
insert into Marcas (Codigo,Nome) values (17,'Dafra')
insert into Marcas (Codigo,Nome) values (18,'Suzuki')
insert into Marcas (Codigo,Nome) values (19,'Yamaha')
insert into Marcas (Codigo,Nome) values (20,'Kawasaki')
insert into Marcas (Codigo,Nome) values (21,'Ducati')
GO
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (1,1,'100',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (2,1,'100 Avant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (3,1,'80',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (4,1,'80 Avant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (5,1,'80 Cabriolet',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (6,1,'A1',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (7,1,'A3',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (8,1,'A3 Cabriolet',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (9,1,'A3 Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (10,1,'A4',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (11,1,'A4 Avant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (12,1,'A4 Cabriolet',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (13,1,'A5',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (14,1,'A6',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (15,1,'A6 Avant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (16,1,'A7',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (17,1,'A8',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (18,1,'Allroad Avant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (19,1,'Q3',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (20,1,'Q5',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (21,1,'Q7',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (22,1,'R8',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (23,1,'RS2 Avant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (24,1,'RS3',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (25,1,'RS3 Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (26,1,'RS4',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (27,1,'RS4 Avant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (28,1,'RS5',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (29,1,'RS6',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (30,1,'RS6 Avant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (31,1,'RS7',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (32,1,'RS Q3',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (33,1,'S3',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (34,1,'S3 Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (35,1,'S4',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (36,1,'S4 Avant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (37,1,'S5',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (38,1,'S6',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (39,1,'S6 Avant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (40,1,'S7',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (41,1,'S8',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (42,1,'SQ5',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (43,1,'TT',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (44,1,'TT RS',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (45,1,'TTS',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (46,2,'1M',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (47,2,'2800',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (48,2,'I3',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (49,2,'I8',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (50,2,'M2',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (51,2,'M3',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (52,2,'M3 Cabrio',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (53,2,'M3 Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (54,2,'M4',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (55,2,'M5',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (56,2,'M5 Touring',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (57,2,'M6',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (58,2,'Série 1',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (59,2,'Série 1 Cabrio',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (60,2,'Série 1 Coupé',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (61,2,'Série 2',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (62,2,'Série 3',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (63,2,'Série 3 Cabrio',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (64,2,'Série 3 Compact',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (65,2,'Série 3 Coupé',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (66,2,'Série 3 Touring',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (67,2,'Série 4',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (68,2,'Série 5',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (69,2,'Série 5 Touring',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (70,2,'Série 6 Cabrio',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (71,2,'Série 6 Coupé',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (72,2,'Série 6 Gran Coupé',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (73,2,'Série 7',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (74,2,'Série 8',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (75,2,'X1',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (76,2,'X2',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (77,2,'X3',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (78,2,'X4',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (79,2,'X5',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (80,2,'X6',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (81,2,'Z3',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (82,2,'Z4 Coupé',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (83,2,'Z4 Roadster',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (84,2,'Z8',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (85,3,'A10',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (86,3,'A20',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (87,3,'Agile',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (88,3,'Astra Hatch',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (89,3,'Astra Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (90,3,'Astra Wagon',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (91,3,'Astrovan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (92,3,'Bel Air',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (93,3,'Blazer',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (94,3,'Bonanza',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (95,3,'Brasil',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (96,3,'Brasinca',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (97,3,'C10',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (98,3,'C14',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (99,3,'C20',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (100,3,'Calibra Coupe',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (101,3,'Camaro',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (102,3,'Caprice Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (103,3,'Caprice Wagon',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (104,3,'Captiva',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (105,3,'Caravan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (106,3,'Cavalier',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (107,3,'Celta',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (108,3,'Chevette Hatch',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (109,3,'Chevette Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (110,3,'Chevy 500',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (111,3,'Cheyenne',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (112,3,'Classic',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (113,3,'Cobalt',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (114,3,'Colorado',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (115,3,'Corsa Hatch',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (116,3,'Corsa Pick-Up',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (117,3,'Corsa Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (118,3,'Corsa Wagon',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (119,3,'Corsica Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (120,3,'Corvette',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (121,3,'Cruze',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (122,3,'Cruze Sport6',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (123,3,'D10',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (124,3,'D20',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (125,3,'Equinox',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (126,3,'HHR',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (127,3,'Impala',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (128,3,'Ipanema',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (129,3,'Kadett',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (130,3,'Kadett Conversivel',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (131,3,'Lumina APV',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (132,3,'Lumina Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (133,3,'Malibu',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (134,3,'Marajo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (135,3,'Meriva',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (136,3,'Montana',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (137,3,'Montana Combo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (138,3,'Monza',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (139,3,'Monza Hatch',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (140,3,'Omega',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (141,3,'Onix',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (142,3,'Opala',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (143,3,'Opala Coupe',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (144,3,'Pick Up Chevrolet',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (145,3,'Prisma',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (146,3,'S10 Cabine Dupla',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (147,3,'S10 Cabine Simples',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (148,3,'Silverado',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (149,3,'Sonic',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (150,3,'Sonic Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (151,3,'Space Van',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (152,3,'Spin',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (153,3,'SS10',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (154,3,'SSR',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (155,3,'Suburban',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (156,3,'Suprema',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (157,3,'Tigra',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (158,3,'Tracker',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (159,3,'Trafic',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (160,3,'TrailBlazer',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (161,3,'Vectra',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (162,3,'Vectra GT',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (163,3,'Veraneio',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (164,3,'Zafira',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (165,4,'Aircross',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (166,4,'AX',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (167,4,'Berlingo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (168,4,'BX',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (169,4,'C3',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (170,4,'C3 Picasso',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (171,4,'C4',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (172,4,'C4 Cactus',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (173,4,'C4 Lounge',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (174,4,'C4 Pallas',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (175,4,'C4 Picasso',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (176,4,'C4 VTR',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (177,4,'C5',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (178,4,'C5 Break',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (179,4,'C5 Tourer',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (180,4,'C6',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (181,4,'C8',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (182,4,'DS3',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (183,4,'DS4',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (184,4,'DS5',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (185,4,'Evasion',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (186,4,'Grand C4 Picasso',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (187,4,'Jumper',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (188,4,'Jumpy',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (189,4,'Xantia',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (190,4,'Xantia Break',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (191,4,'XM',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (192,4,'XM Break',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (193,4,'Xsara',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (194,4,'Xsara Break',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (195,4,'Xsara Coupe',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (196,4,'Xsara Picasso',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (197,4,'ZX',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (198,5,'147',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (199,5,'147 Furgao',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (200,5,'147 Pick-Up',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (201,5,'500',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (202,5,'Argo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (203,5,'Brava',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (204,5,'Bravo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (205,5,'Cinquecento',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (206,5,'Coupe',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (207,5,'Cronos',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (208,5,'Doblò',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (209,5,'Doblò Cargo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (210,5,'Ducato',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (211,5,'Duna',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (212,5,'Elba',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (213,5,'Fiorino',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (214,5,'Fiorino Pick-Up',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (215,5,'Freemont',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (216,5,'Grand Siena',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (217,5,'Idea',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (218,5,'Linea',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (219,5,'Marea',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (220,5,'Marea Weekend',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (221,5,'Mobi',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (222,5,'Oggi',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (223,5,'Palio',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (224,5,'Palio Weekend',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (225,5,'Panorama',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (226,5,'Premio',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (227,5,'Punto',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (228,5,'Punto Cabrio',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (229,5,'Siena',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (230,5,'Stilo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (231,5,'Strada',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (232,5,'Tempra',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (233,5,'TipoCodigo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (234,5,'Toro',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (235,5,'Uno',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (236,5,'Uno Furgão',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (237,5,'Uno Mille',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (238,5,'Uno Pick-Up',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (239,5,'Weekend',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (240,6,'Aerostar',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (241,6,'Aspire',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (242,6,'Belina',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (243,6,'Bronco',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (244,6,'Club Wagon',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (245,6,'Contour',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (246,6,'Corcel',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (247,6,'Coupe Deluxe',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (248,6,'Courier',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (249,6,'Courier Van',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (250,6,'Crown Victoria',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (251,6,'Del Rey',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (252,6,'Del Rey Belina / Scala',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (253,6,'EcoSport',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (254,6,'Edge',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (255,6,'Escape',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (256,6,'Escort',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (257,6,'Escort Conversivel',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (258,6,'Escort Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (259,6,'Escort SW',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (260,6,'Excursion',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (261,6,'Expedition',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (262,6,'Explorer',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (263,6,'F-1',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (264,6,'F-100',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (265,6,'F-1000',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (266,6,'F-150',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (267,6,'F-250',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (268,6,'F-350',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (269,6,'F-4000',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (270,6,'F75',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (271,6,'Fairlane',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (272,6,'Fiesta Hatch',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (273,6,'Fiesta Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (274,6,'Focus Hatch',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (275,6,'Focus Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (276,6,'Ford 1929',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (277,6,'Furglaine',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (278,6,'Fusion',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (279,6,'Galaxie',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (280,6,'GT',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (281,6,'Ibiza',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (282,6,'Jeep',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (283,6,'Ka+',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (284,6,'Ka Hatch',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (285,6,'Landau',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (286,6,'Lincoln',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (287,6,'Maverick',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (288,6,'Mondeo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (289,6,'Mondeo Wagon',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (290,6,'Mustang',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (291,6,'New Fiesta Hatch',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (292,6,'New Fiesta Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (293,6,'Pampa',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (294,6,'Probe',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (295,6,'Ranger (Cabine Dupla)',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (296,6,'Ranger (Cabine Simples-Estendida)',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (297,6,'Rural',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (298,6,'Taurus',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (299,6,'Taurus Wagon',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (300,6,'Thunderbird',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (301,6,'Transit',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (302,6,'Verona',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (303,6,'Versailles',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (304,6,'Versailles Royale',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (305,6,'Windstar',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (306,7,'Accord',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (307,7,'Accord Coupe',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (308,7,'Accord Wagon',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (309,7,'City',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (310,7,'Civic',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (311,7,'Civic Coupe',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (312,7,'Civic Hatch',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (313,7,'Civic Targa',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (314,7,'CR-V',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (315,7,'Fit',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (316,7,'HR-V',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (317,7,'Legend',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (318,7,'NSX',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (319,7,'Odyssey',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (320,7,'Passport',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (321,7,'Prelude',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (322,7,'Quadriciclo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (323,7,'WR-V',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (324,8,'Accent',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (325,8,'Accent Hatch',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (326,8,'Atos',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (327,8,'Azera',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (328,8,'Coupe FX',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (329,8,'Creta',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (330,8,'Elantra',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (331,8,'Elantra Wagon',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (332,8,'Equus',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (333,8,'Excel',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (334,8,'Galloper',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (335,8,'Genesis',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (336,8,'H1',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (337,8,'H100',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (338,8,'HB20',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (339,8,'HB20S',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (340,8,'HB20X',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (341,8,'HR',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (342,8,'i30',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (343,8,'i30 CW',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (344,8,'ix35',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (345,8,'Matrix',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (346,8,'Porter',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (347,8,'Santa Fe',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (348,8,'Scoupe',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (349,8,'Sonata',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (350,8,'Terracan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (351,8,'Trajet',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (352,8,'Tucson',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (353,8,'Veloster',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (354,8,'Veracruz',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (355,9,'Cherokee',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (356,9,'Commander',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (357,9,'Compass',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (358,9,'Grand Cherokee',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (359,9,'Liberty',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (360,9,'Renegade',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (361,9,'Wrangler',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (362,10,'Besta',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (363,10,'Bongo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (364,10,'Cadenza',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (365,10,'Carens',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (366,10,'Carnival',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (367,10,'Cerato',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (368,10,'Ceres',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (369,10,'Clarus',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (370,10,'Grand Carnival',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (371,10,'Magentis',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (372,10,'Mohave',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (373,10,'Opirus',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (374,10,'Optima',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (375,10,'Picanto',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (376,10,'Quoris',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (377,10,'Rio',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (378,10,'Sephia',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (379,10,'Shuma',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (380,10,'Sorento',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (381,10,'Soul',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (382,10,'Sportage',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (383,10,'Stinger',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (384,11,'3000',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (385,11,'Airtrek',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (386,11,'ASX',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (387,11,'Colt',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (388,11,'Diamant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (389,11,'Eclipse',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (390,11,'Eclipse Cross',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (391,11,'Expo LRV',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (392,11,'Expo SP Van',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (393,11,'Galant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (394,11,'Grandis',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (395,11,'L200',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (396,11,'L200 Outdoor',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (397,11,'L200 Triton',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (398,11,'L300',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (399,11,'Lancer',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (400,11,'Lancer Evolution',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (401,11,'Lancer Sportback',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (402,11,'Mirage',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (403,11,'Montero',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (404,11,'Outlander',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (405,11,'Pajero',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (406,11,'Pajero Dakar',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (407,11,'Pajero Full',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (408,11,'Pajero Sport',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (409,11,'Pajero TR4',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (410,11,'Space Wagon',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (411,12,'350Z',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (412,12,'370Z',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (413,12,'Altima',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (414,12,'Armada',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (415,12,'AX',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (416,12,'Frontier',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (417,12,'Grand Livina',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (418,12,'GT-R',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (419,12,'Juke',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (420,12,'Kicks',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (421,12,'King Cab',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (422,12,'LEAF',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (423,12,'Livina',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (424,12,'March',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (425,12,'Maxima',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (426,12,'Micra',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (427,12,'Murano',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (428,12,'NX 2000',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (429,12,'Pathfinder',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (430,12,'Pick Up D21',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (431,12,'Pick Up D22',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (432,12,'Primera',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (433,12,'Quest',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (434,12,'Sentra',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (435,12,'Stanza',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (436,12,'SX',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (437,12,'Terrano II',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (438,12,'Tiida',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (439,12,'Tiida Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (440,12,'Versa',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (441,12,'XTerra',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (442,12,'XTRAIL',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (443,12,'ZX',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (444,13,'106',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (445,13,'2008',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (446,13,'205',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (447,13,'205 Cabriolet',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (448,13,'206',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (449,13,'206 CC',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (450,13,'206 SW',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (451,13,'207',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (452,13,'207 Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (453,13,'207 SW',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (454,13,'207 SW Escapade',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (455,13,'208',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (456,13,'3008',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (457,13,'306',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (458,13,'306 Break',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (459,13,'306 Cabriolet',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (460,13,'306 Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (461,13,'307',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (462,13,'307 CC',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (463,13,'307 Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (464,13,'307 SW',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (465,13,'308',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (466,13,'308 CC',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (467,13,'405',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (468,13,'405 Break',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (469,13,'406',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (470,13,'406 Break',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (471,13,'406 Coupe',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (472,13,'407',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (473,13,'407 SW',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (474,13,'408',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (475,13,'5008',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (476,13,'504',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (477,13,'505',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (478,13,'508',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (479,13,'605',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (480,13,'607',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (481,13,'806',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (482,13,'807',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (483,13,'Boxer',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (484,13,'Expert',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (485,13,'Hoggar',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (486,13,'Partner',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (487,13,'RCZ',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (488,14,'19',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (489,14,'21',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (490,14,'Captur',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (491,14,'Clio',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (492,14,'Clio Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (493,14,'Duster',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (494,14,'Duster Oroch',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (495,14,'Fluence',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (496,14,'Grand Scenic',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (497,14,'Kangoo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (498,14,'Kangoo Express',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (499,14,'Kwid',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (500,14,'Laguna',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (501,14,'Laguna Grand Tour',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (502,14,'Logan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (503,14,'Master',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (504,14,'Master Chassi',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (505,14,'Megane Cabriolet',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (506,14,'Megane Grand Tour',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (507,14,'Megane Hatch',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (508,14,'Megane Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (509,14,'Safrane ',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (510,14,'Sandero',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (511,14,'Sandero Stepway',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (512,14,'Scenic',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (513,14,'Symbol',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (514,14,'Trafic',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (515,14,'Twingo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (516,14,'Zoe',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (517,15,'Avalon ',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (518,15,'Bandeirante Jipe',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (519,15,'Bandeirante Picape',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (520,15,'Camry ',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (521,15,'Camry Wagon',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (522,15,'Celica',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (523,15,'Corolla',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (524,15,'Corolla Fielder',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (525,15,'Corolla Wagon',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (526,15,'Corona Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (527,15,'Etios Hatch',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (528,15,'Etios Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (529,15,'FJ Cruiser',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (530,15,'Hilux Cabine Dupla',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (531,15,'Hilux Cabine Simples',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (532,15,'Land Cruiser Prado',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (533,15,'MR2',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (534,15,'Paseo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (535,15,'Previa',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (536,15,'Prius',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (537,15,'RAV4',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (538,15,'Sequoia',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (539,15,'Sienna',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (540,15,'Supra',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (541,15,'SW4',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (542,15,'T100',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (543,15,'Tacoma',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (544,15,'Trip',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (545,15,'Tundra',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (546,15,'Yaris Hatch',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (547,15,'Yaris Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (548,16,'Amarok',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (549,16,'Apollo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (550,16,'Bora',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (551,16,'Brasília',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (552,16,'Caravelle',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (553,16,'CC',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (554,16,'Corrado',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (555,16,'CrossFox',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (556,16,'Eos',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (557,16,'Eurovan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (558,16,'Fox',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (559,16,'Fusca',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (560,16,'Gol',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (561,16,'Golf',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (562,16,'Golf Cabrio',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (563,16,'Gol Furgao',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (564,16,'Golf Variant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (565,16,'Jetta',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (566,16,'Jetta Variant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (567,16,'Karmann Ghia',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (568,16,'Kombi',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (569,16,'Kombi Furgão',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (570,16,'Kombi Pick-Up',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (571,16,'Logus',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (572,16,'New Beetle',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (573,16,'New Beetle Cabriolet',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (574,16,'Parati',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (575,16,'Passat',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (576,16,'Passat CC',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (577,16,'Passat Variant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (578,16,'Pointer',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (579,16,'Polo',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (580,16,'Polo Classic',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (581,16,'Polo Sedan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (582,16,'Puma',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (583,16,'Quantum',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (584,16,'Santana',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (585,16,'Saveiro',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (586,16,'Scirocco',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (587,16,'SP2',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (588,16,'SpaceCross',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (589,16,'SpaceFox',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (590,16,'Tanger',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (591,16,'T-Cross',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (592,16,'Tiguan',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (593,16,'TL',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (594,16,'Touareg',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (595,16,'Up!',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (596,16,'Van',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (597,16,'Variant',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (598,16,'Virtus',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (599,16,'Voyage',0)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (600,17,'Apache',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (601,17,'Cityclass 200i',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (602,17,'Fiddle',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (603,17,'Horizon',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (604,17,'Kansas',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (605,17,'Laser',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (606,17,'Maxsym 400i',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (607,17,'Next',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (608,17,'Riva',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (609,17,'Roadwin',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (610,17,'Smart',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (611,17,'Speed',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (612,17,'Super',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (613,17,'Sym Citycom',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (614,17,'Zig',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (615,7,'America Classic',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (616,7,'BIZ 100',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (617,7,'BIZ 110i',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (618,7,'BIZ 125',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (619,7,'C 100 Dream',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (620,7,'CB 1000R',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (621,7,'CB 1300',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (622,7,'CB 300R',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (623,7,'CB 400',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (624,7,'CB 450',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (625,7,'CB 500',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (626,7,'CB 600 (Hornet)',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (627,7,'CB 650',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (628,7,'CB 750',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (629,7,'CB 900',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (630,7,'CB Twister',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (631,7,'CBR 1000',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (632,7,'CBR 1100',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (633,7,'CBR 250R',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (634,7,'CBR 450',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (635,7,'CBR 500',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (636,7,'CBR 600',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (637,7,'CBR 650',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (638,7,'CBR 900',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (639,7,'CBR 929',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (640,7,'CBR 954',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (641,7,'CBX 150',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (642,7,'CBX 200',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (643,7,'CBX 250',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (644,7,'CBX 750',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (645,7,'CG 125',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (646,7,'CG 150',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (647,7,'CG 160',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (648,7,'CH 125 R',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (649,7,'CRF',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (650,7,'CRF 1000',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (651,7,'CTX 700',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (652,7,'Elite 125',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (653,7,'Gold Wing',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (654,7,'LEAD',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (655,7,'Magna 750',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (656,7,'ML 125',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (657,7,'NC 700X',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (658,7,'NC 750X',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (659,7,'NX 150',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (660,7,'NX 200',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (661,7,'NX 350',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (662,7,'NX 4 Falcon',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (663,7,'NXR 125',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (664,7,'NXR 150',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (665,7,'NXR 160',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (666,7,'PCX',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (667,7,'POP',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (668,7,'SH',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (669,7,'Shadow',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (670,7,'Shadow Am',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (671,7,'Shadow Vt',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (672,7,'Silver Wing',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (673,7,'Super Hawk',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (674,7,'TRX (Quadriciclo)',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (675,7,'Valkyrie',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (676,7,'VFR',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (677,7,'VT 600',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (678,7,'VTX',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (679,7,'X-ADV',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (680,7,'XL 1000',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (681,7,'XL 125',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (682,7,'Xl 250',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (683,7,'XL 350',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (684,7,'XL 700V',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (685,7,'XLR 125',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (686,7,'XLX 250',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (687,7,'XLX 350',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (688,7,'XR 200',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (689,7,'XR 250',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (690,7,'XR 650',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (691,7,'XRE 190',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (692,7,'XRE 300',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (693,18,'Address Ae',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (694,18,'Address Ag',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (695,18,'Bandit 1200',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (696,18,'Bandit 1200S',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (697,18,'Bandit 1250',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (698,18,'Bandit 1250S',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (699,18,'Bandit 600',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (700,18,'Bandit 600S',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (701,18,'Bandit 650',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (702,18,'Bandit 650S',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (703,18,'Boulevard',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (704,18,'Burgman',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (705,18,'Dl 1000',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (706,18,'Dl 650',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (707,18,'Dr 350',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (708,18,'Dr 650',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (709,18,'Dr 800',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (710,18,'Dr Z 400',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (711,18,'En 125',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (712,18,'Freewind',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (713,18,'Gladius',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (714,18,'Gs 120',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (715,18,'Gs 500',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (716,18,'Gsr 125',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (717,18,'Gsr 150i',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (718,18,'Gsr 750A ',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (719,18,'Gsx 1100',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (720,18,'Gsx 1250FA',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (721,18,'Gsx 1300',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (722,18,'Gsx 650F',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (723,18,'Gsx 750',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (724,18,'Gsx R 1000',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (725,18,'Gsx R 1000 (25anos)',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (726,18,'Gsx R 1100',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (727,18,'Gsx R 1300',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (728,18,'Gsx R 750',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (729,18,'Gsx S 1000',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (730,18,'Gsx S 1000FA',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (731,18,'Gsx S 750',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (732,18,'Hayabusa',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (733,18,'Inazuma',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (734,18,'Intruder',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (735,18,'Katana',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (736,18,'Lets II',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (737,18,'Marauder',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (738,18,'Rf 600',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (739,18,'Rf 900',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (740,18,'RM-Z',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (741,18,'Savage',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (742,18,'SV 650',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (743,18,'Tl 1000',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (744,18,'Vx 800cc',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (745,19,'Axis 90',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (746,19,'Bws 50',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (747,19,'Crypton',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (748,19,'Crypton 100',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (749,19,'Drag Star 1100',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (750,19,'Drag Star 650',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (751,19,'Drag Star Xvs 650',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (752,19,'Dt 180 Z',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (753,19,'Dt 200',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (754,19,'Fazer 250 ie',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (755,19,'Fjr 1300',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (756,19,'Fz 6 600',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (757,19,'Fz1',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (758,19,'Fz6',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (759,19,'Fz6 s',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (760,19,'Fzr 1000',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (761,19,'Fzr 600',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (762,19,'Grizzly',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (763,19,'Jog 50',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (764,19,'Jog Teen 50',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (765,19,'Magesty',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (766,19,'MT 01',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (767,19,'MT 03',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (768,19,'MT 07',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (769,19,'MT 09 ',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (770,19,'Neo',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (771,19,'NMax',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (772,19,'Rd 125',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (773,19,'Rd 135',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (774,19,'Rd 350',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (775,19,'Rdz 125',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (776,19,'Rdz 135',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (777,19,'Royal Star 1300',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (778,19,'Tdm 225',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (779,19,'Tdm 850',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (780,19,'Tdm 900',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (781,19,'Tdr 180',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (782,19,'Tmax',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (783,19,'Trx 850',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (784,19,'TT-R',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (785,19,'V Max 1200',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (786,19,'V Max 1700',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (787,19,'V Star 1100 Classic',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (788,19,'Virago 750',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (789,19,'Wr',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (790,19,'Xj6 F',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (791,19,'Xj6 N',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (792,19,'Xjr 1200',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (793,19,'XT 1200Z',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (794,19,'XT 225',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (795,19,'XT 600',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (796,19,'XT 660',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (797,19,'Xtz 125 E',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (798,19,'Xtz 125 K',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (799,19,'Xtz 125 X',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (800,19,'Xtz 150 Crosser',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (801,19,'Xtz 250 Lander',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (802,19,'Xtz 250 Tenere',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (803,19,'Xtz 750',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (804,19,'Xv 1100',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (805,19,'Xv 250 (Virago)',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (806,19,'Xv 535',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (807,19,'Xvs Midnight',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (808,19,'YBR 125',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (809,19,'YBR 125 Factor',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (810,19,'YBR 150 Factor',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (811,19,'YFM',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (812,19,'YS 150 Fazer',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (813,19,'YS 250 Fazer',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (814,19,'YZ',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (815,19,'YZF 1000',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (816,19,'YZF 600',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (817,19,'YZF 750',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (818,19,'YZF R1',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (819,19,'YZF R3',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (820,19,'YZF R6',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (821,20,'Concours',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (822,20,'D tracker x',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (823,20,'ER 5',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (824,20,'ER 6n',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (825,20,'KLX',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (826,20,'KX',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (827,20,'KZ',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (828,20,'Maxi II',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (829,20,'Ninja',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (830,20,'Versys',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (831,20,'Voyager',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (832,20,'Vulcan',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (833,20,'Z 1000',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (834,20,'Z 300',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (835,20,'Z 650',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (836,20,'Z 750',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (837,20,'Z 800',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (838,20,'Z 900',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (839,2,'C 600',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (840,2,'F 650',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (841,2,'F 700',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (842,2,'F 800',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (843,2,'G 310',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (844,2,'G 450',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (845,2,'G 650',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (846,2,'K 1100',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (847,2,'K 1200',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (848,2,'K 1300',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (849,2,'K 1600',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (850,2,'R 1100',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (851,2,'R 1150',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (852,2,'R 1200',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (853,2,'S 1000',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (854,21,'Desmosedici',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (855,21,'Diavel',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (856,21,'Hypermotard',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (857,21,'Hyperstrada',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (858,21,'Monster',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (859,21,'Multistrada',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (860,21,'Scrambler',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (861,21,'Sportclassic',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (862,21,'Streetfighter',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (863,21,'Super Sport 900 ss',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (864,21,'Super Touring St 2 900',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (865,21,'Super Touring St 4 900',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (866,21,'Superbike',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (867,21,'Superbike 749',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (868,21,'Superbike 916',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (869,21,'Superbike 996',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (870,21,'Superbike 998',1)
INSERT INTO ModelosVeiculos (Codigo,MarcaCodigo,Modelo,TipoCodigo) VALUES (871,21,'Superbike 999',1)

